{% set name = "ddt" %}
{% set version = "1.4.0" %}
{% set sha256 = "a76a6c6ffd3d4eb12ec42126d13be8406d6e53a6ea7b283f07d6595c24a10e73" %}
{% set repo = "txels" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ repo }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - flake8
    - nose
    - six >=1.4.0
    - pyyaml
    - mock
    - pytest
  source_files:
    - test/*
  commands:
    - py.test

about:
  home: https://github.com/txels/ddt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: DDT (Data-Driven Tests) allows you to multiply one test case by running it with different test data, and make it appear as multiple test cases.
  description: DDT (Data-Driven Tests) allows you to multiply one test case by running it with different test data, and make it appear as multiple test cases.
  doc_url: http://ddt.readthedocs.io/en/latest/
  dev_url: https://github.com/txels/ddt

extra:
  recipe-maintainers:
    - CJ-Wright
