{% set version = "1.6.0" %}

package:
  name: ddt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/ddt/ddt-{{ version }}.tar.gz
  sha256: f71b348731b8c78c3100bffbd951a769fbd439088d1fdbb3841eee019af80acd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  requires:
    - pip
    - pytest-cov
    - six >=1.4.0
    - pyyaml
  source_files:
    - test/*
  commands:
    - pip check
    - pytest test -vv --cov=ddt --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under=97

about:
  home: https://github.com/datadriventests/ddt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Data-Driven/Decorated Tests
  description: DDT (Data-Driven Tests) allows you to multiply one test case by running it with different test data, and make it appear as multiple test cases.
  doc_url: https://ddt.readthedocs.io

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
