{% set version = "1.7.1" %}

package:
  name: ddt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/ddt/ddt-{{ version }}.tar.gz
  sha256: 1a4472c477bf766f75f7b1efb628656ff3c35ff3f6c821129ae8e328fff8a9a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  requires:
    - aiounittest >=1.4.0
    - pip
    - pytest-cov
    - pyyaml
    - six >=1.4.0
  source_files:
    - test/*
  commands:
    - pip check
    - pytest test -vv --cov=ddt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=97

about:
  home: https://github.com/datadriventests/ddt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Data-Driven/Decorated Tests
  description: DDT (Data-Driven Tests) allows you to multiply one test case by running it with different test data, and make it appear as multiple test cases.
  doc_url: https://ddt.readthedocs.io
  doc_source_url: https://github.com/datadriventests/ddt/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
